title: Ajith George # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Development Engineer in Test
  <br><br>
  QA guy - Learner - Awesome Dude
  Explore- Dream - Discover"
  <br><br>
  <a href="https://www.linkedin.com/in/ajith-george92/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
